import type { Metadata } from "next";
import localFont from "next/font/local";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--fonts-main",
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Camter",
  description: "Generated by Евгений Павлов",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
      
        className={`${raleway.variable} `}
      >
        <Header></Header>
        {children}
        
      </body>
    </html>
  );
}
